import { readFileSync } from "node:fs";
import path from "node:path";

import { describe, expect, test } from "vitest";

import { cosineSimilarity } from "../../retrieval/cosine-similarity.js";
import { testProjectRoot } from "../../test-support/helpers.js";
import { NEAR_DUPLICATE_SIMILARITY_THRESHOLD } from "../worker-result-applier.js";
import { corpusEmbeddingDigest } from "./corpus-embedding-digest.js";

/**
 * Calibrates NEAR_DUPLICATE_SIMILARITY_THRESHOLD against real bge-small-en-v1.5
 * vectors for the pinned retrieval corpus, regenerated by
 * `npx tsx scripts/generate-corpus-embeddings.ts`.
 *
 * The vectors are committed rather than computed here so the suite stays
 * hermetic -- the real model is a ~133MB download.
 */
const fixturePath = path.join(testProjectRoot, "src", "orchestration", "__tests__", "fixtures", "corpus-embeddings.json");
const corpusPath = path.join(testProjectRoot, "src", "eval", "retrieval", "fixtures", "corpus.json");

type EmbeddedLearning = { id: string; repo: string; title: string; vector: string };
type CorpusEmbeddings = { model: string; dims: number; inputDigest: string; learnings: EmbeddedLearning[] };
type CorpusLearning = { id: string; title: string; content: string };

// `Buffer.from(base64)` returns a view into a shared pool, so `.buffer` is the
// whole pool. Slicing by byteOffset/byteLength copies just this vector -- the
// same trap `fromVectorBlob` guards in the sqlite repo.
const decodeVector = (base64: string): Float32Array => {
  const buffer = Buffer.from(base64, "base64");
  return new Float32Array(buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength));
};

const fixture = JSON.parse(readFileSync(fixturePath, "utf8")) as CorpusEmbeddings;
const corpus = JSON.parse(readFileSync(corpusPath, "utf8")) as CorpusLearning[];
const vectorsById = new Map(fixture.learnings.map((learning) => [learning.id, decodeVector(learning.vector)]));

const similarity = (leftId: string, rightId: string): number => {
  const left = vectorsById.get(leftId);
  const right = vectorsById.get(rightId);
  if (!left || !right) {
    throw new Error(`corpus fixture is missing ${!left ? leftId : rightId}`);
  }

  return cosineSimilarity(left, right);
};

/**
 * The near-identical pairs labelled by ENG-5444: same rule, stored twice under
 * different titles. Each of these is what write-time flagging must catch.
 */
const NEAR_IDENTICAL_PAIRS: Array<[string, string, string]> = [
  ["01KT3AT1DE6YSSBGA4W0874T79", "01KVSNHYK5NRJ5S4WAKV3ZTG7C", "client-side DataTable must fetchAllPages"],
  ["01KT0YN8XXHBR7EHWYJZS75SC0", "01KT1236TBD689A21C8J41ANE6", "run `yarn run check`, not `yarn check`"],
  ["01KTNHKJ7ARB311414PWDZCT9H", "01KTNKMZTNN1DGEZS3CY3Q61WP", "verify foreman UI via vite dev proxy"],
  ["01KT124Y4Z5YSZNB91YM80DATP", "01KTWSMJQME1JRYM6V53SN9A4C", "take the PR diff from origin/master, not local master"],
  ["01KTNRVZ88EGXEFX5ES9ZKAA5T", "01KTNSARRSQRBVQCH4JS0YYJZ2", "scout-run summary is written at completeScoutRun"],
];

/**
 * Legitimate neighbours: same repo, same topic, overlapping vocabulary -- but
 * each encodes a rule the other does not. Flagging these would be a false
 * positive, so they set the ceiling the threshold has to clear.
 */
const DISTINCT_NEIGHBOURS: Array<[string, string, string]> = [
  ["01KTNSARRSQRBVQCH4JS0YYJZ2", "01KTNSRG6A00NC4BKRJFZT0ACK", "scout-run: where to write vs which layer to test"],
  ["01KT11MCNRCFVBJAD5KFZHRAJW", "01KT5F65A02FAMRAA348HWP7DW", "prompt token guards: cause vs remedy"],
  ["01KT0ZJE4X59QR63CBW27JTRNM", "01KTNKKFHKB0K22TY68MRYVJWY", "assert payload fields vs assert the structured contract"],
  ["01KT3BDWVWY838GZY3X5ANABW3", "01KVSNHYK60455PQD2Y8H5Y137", "retry dedup: cache the id vs sequential POSTs"],
  ["01KT0ZJE4X59QR63CBW27JTRNM", "01KT102VABWB0K9GG7S2M2XBKX", "assert field values vs assert serialized keys"],
];

describe("near-duplicate threshold calibration", () => {
  test("the fixture holds one real-model vector per corpus learning", () => {
    expect(fixture.model).toBe("bge-small-en-v1.5");
    expect(fixture.dims).toBe(384);
    expect(vectorsById.size).toBe(fixture.learnings.length);
    expect(fixture.learnings.every((learning) => decodeVector(learning.vector).length === fixture.dims)).toBe(true);
  });

  test("the fixture's vectors were computed from the corpus as it stands now", () => {
    // Everything below calibrates a threshold against these vectors. Compared
    // only against itself the fixture cannot detect a corpus edit or a change to
    // `learningEmbeddingText`, and the whole suite would stay green while
    // measuring text the corpus no longer carries. Regenerate with
    // `npx tsx scripts/generate-corpus-embeddings.ts` when this fails -- and
    // re-derive the threshold, because the window it sits in will have moved.
    expect(fixture.inputDigest).toBe(corpusEmbeddingDigest(corpus));
    expect(fixture.learnings.map((learning) => learning.id)).toEqual(corpus.map((learning) => learning.id));
  });

  test.each(NEAR_IDENTICAL_PAIRS)("flags the near-identical pair: %s / %s (%s)", (leftId, rightId) => {
    expect(similarity(leftId, rightId)).toBeGreaterThanOrEqual(NEAR_DUPLICATE_SIMILARITY_THRESHOLD);
  });

  test.each(DISTINCT_NEIGHBOURS)("leaves the same-topic neighbour unflagged: %s / %s (%s)", (leftId, rightId) => {
    expect(similarity(leftId, rightId)).toBeLessThan(NEAR_DUPLICATE_SIMILARITY_THRESHOLD);
  });

  test("the threshold sits inside the window separating duplicates from distinct neighbours", () => {
    const weakestDuplicate = Math.min(...NEAR_IDENTICAL_PAIRS.map(([left, right]) => similarity(left, right)));
    const strongestDistinct = Math.max(...DISTINCT_NEIGHBOURS.map(([left, right]) => similarity(left, right)));

    // Asserted to 4dp so a model or corpus change that moves the window fails
    // here -- with the numbers needed to re-pick the threshold -- rather than
    // silently shifting what counts as a duplicate.
    expect(weakestDuplicate).toBeCloseTo(0.9151, 4);
    expect(strongestDistinct).toBeCloseTo(0.9067, 4);

    expect(strongestDistinct).toBeLessThan(NEAR_DUPLICATE_SIMILARITY_THRESHOLD);
    expect(NEAR_DUPLICATE_SIMILARITY_THRESHOLD).toBeLessThan(weakestDuplicate);
  });

  test("the threshold flags a small, hand-checkable slice of the corpus", () => {
    const learnings = fixture.learnings;
    let flagged = 0;
    for (let left = 0; left < learnings.length; left += 1) {
      for (let right = left + 1; right < learnings.length; right += 1) {
        if (similarity(learnings[left]!.id, learnings[right]!.id) >= NEAR_DUPLICATE_SIMILARITY_THRESHOLD) {
          flagged += 1;
        }
      }
    }

    // 7 of 6328 pairs. Beyond the 5 labelled above, the threshold catches the
    // third member of the fetchAllPages trio and a continuation-prompt pair
    // whose newer entry supersedes the older -- both genuine duplicates that
    // the ENG-5444 pass missed, not false positives.
    expect(flagged).toBe(7);
  });
});
